//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemReader.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ItemReader.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BagIcon {
            get {
                object obj = ResourceManager.GetObject("BagIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Mini-Soo\Projects\test.
        /// </summary>
        internal static string DEBUG_FOLDER {
            get {
                return ResourceManager.GetString("DEBUG_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BagIcon.png - Paint.
        /// </summary>
        internal static string GAME_WINDOW {
            get {
                return ResourceManager.GetString("GAME_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mora
        ///MysticEnhancementOre
        ///FineEnhancementOre
        ///EnhancementOre
        ///HerosWit
        ///AdventurersExperience
        ///WanderersAdvice
        ///SlimeConcentrate
        ///SlimeSecretions
        ///SlimeCondensate
        ///OminousMask
        ///StainedMask
        ///DamagedMask
        ///ForbiddenCurseScroll
        ///SealedScroll
        ///DiviningScroll
        ///WeatheredArrowhead
        ///SharpArrowhead
        ///FirmArrowhead
        ///BlackCrystalHorn
        ///BlackBronzeHorn
        ///HeavyHorn
        ///LeyLineSprout
        ///DeadLeyLineLeaves
        ///DeadLeyLineBranch
        ///ChaosCore
        ///ChaosCircuit
        ///ChaosDevice
        ///MistGrassWick
        ///MistGrass
        ///MistGrassPollen
        ///InspectorsSacrificialKnife
        ///AgentsSacrificialKnife
        ///Hunte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemList {
            get {
                return ResourceManager.GetString("ItemList", resourceCulture);
            }
        }
    }
}
